AppWebDBProject/AppWebDB/Controllers/DatabaseController.cs
using System.Net;
using System.Security.Claims;
using System.Text;
using Domain.Domain;
using Domain.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Service.Interface;

namespace AppWebDB.Controllers
{
    public class DatabaseController : Controller
    {
        private readonly IDatabaseService _databaseService;
        //private readonly HttpClient _flaskClient;
        private readonly IDatabaseSchemaRetriever _databaseSchemaRetriever;
        private readonly ICheckDBConnection _checkDBConnection;

        public DatabaseController(IDatabaseService databaseService, IDatabaseSchemaRetriever databaseSchemaRetriever, ICheckDBConnection checkDBConnection)
        {
            _databaseService = databaseService;
            _databaseSchemaRetriever = databaseSchemaRetriever;
            _checkDBConnection = checkDBConnection;
        }

        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            List<Database> db = _databaseService.GetDatabasesForUser(userId);
            return View(db);
        }

        public IActionResult Create() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync([Bind("Id,Name,Username,Password,Host,DatabaseName")] Database db)
        {
            if (ModelState.IsValid)
            {
                //Check DB credentials whether they are true
                var cn = await _checkDBConnection.CheckDatabaseCredentialsAsync(db.Host, db.DatabaseName, db.Username, db.Password);

                if (cn == true)
                {
                    // Database connection successful, proceed with creating the database
                    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    db.Id = Guid.NewGuid();
                    _databaseService.CreateNewDatabase(db, userId);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    // Database connection failed, return error message
                    ModelState.AddModelError(string.Empty, "Failed to connect to the database. Please check and re-enter your credentials.");
                    return View(db);
                }

                //BELOW COMMENTED CODE FOR WORKING WITH PYTHON FLASK APP
                // Send a POST request to the Flask app to check database connection
                //var formData = new Dictionary<string, string>
                //{
                //    { "dbUsername", db.Username },
                //    { "dbPass", db.Password },
                //    { "dbHost", db.Host },
                //    { "dbName", db.DatabaseName }
                //};

                //var connectResponse = await _flaskClient.PostAsync("http://localhost:5000/connect", new FormUrlEncodedContent(formData));

                //if (connectResponse.IsSuccessStatusCode)
                //{
                //    // Database connection successful, proceed with creating the database
                //    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                //    db.Id = Guid.NewGuid();
                //    _databaseService.CreateNewDatabase(db, userId);
                //    return RedirectToAction(nameof(Index));
                //}
                //else
                //{
                //    // Database connection failed, return error message
                //    ModelState.AddModelError(string.Empty, "Failed to connect to the database. Please check and re-enter your credentials.");
                //    return View(db);
                //}
            }
            return View(db);
        }

        public IActionResult Edit(Guid? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var db = _databaseService.GetDetailsForDatabase(id);
            if(db == null)
            {
                return NotFound();
            }
            return View(db);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync(Guid id, [Bind("Id,Name,Username,Password,Host,DatabaseName")] Database db)
        {
            if (id != db.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    //Check DB credentials whether they are true
                    var cn = await _checkDBConnection.CheckDatabaseCredentialsAsync(db.Host, db.DatabaseName, db.Username, db.Password);
                    if(cn==true)
                    {
                        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                        _databaseService.UpdateExistingDatabase(db, userId);
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Failed to connect to the database. Please check and re-enter your credentials.");
                        return View(db);
                    }

                    //BELOW COMMENTED CODE FOR WORKING WITH PYTHON FLASK APP
                    //var formData = new Dictionary<string, string>
                    //{
                    //    { "dbUsername", db.Username },
                    //    { "dbPass", db.Password },
                    //    { "dbHost", db.Host },
                    //    { "dbName", db.DatabaseName }
                    //};

                    //var connectResponse = await _flaskClient.PostAsync("http://localhost:5000/connect", new FormUrlEncodedContent(formData));

                    //if (connectResponse.IsSuccessStatusCode)
                    //{
                    //    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    //    _databaseService.UpdateExistingDatabase(db, userId);
                    //}
                    //else
                    //{
                    //    // Database connection failed, return error message
                    //    ModelState.AddModelError(string.Empty, "Failed to connect to the database. Please check and re-enter your credentials.");
                    //    return View(db);
                    //}
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(db);
        }

        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var db = _databaseService.GetDetailsForDatabase(id);
            if (db == null)
            {
                return NotFound();
            }

            return View(db);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _databaseService.DeleteDatabase(id, userId);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult SeeQuestions(Guid id)
        {
            var db = _databaseService.GetDetailsForDatabase(id);
            return RedirectToAction("Index","Question", new {id = id});
        }
    }
}

AppWebDBProject/AppWebDB/Views/Database/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Domain.Domain.Database

<h1>Create</h1>

<h4>Database</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Host" class="control-label"></label>
                <input asp-for="Host" class="form-control" />
                <span asp-validation-for="Host" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatabaseName" class="control-label"></label>
                <input asp-for="DatabaseName" class="form-control" />
                <span asp-validation-for="DatabaseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AppWebDBProject/AppWebDB/Views/Database/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Domain.Domain.Database

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Database</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Host)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Host)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DatabaseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DatabaseName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppWebDBProject/AppWebDB/Views/Database/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Domain.Domain.Database

<h4>Database</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Host" class="control-label"></label>
                <input asp-for="Host" class="form-control" />
                <span asp-validation-for="Host" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatabaseName" class="control-label"></label>
                <input asp-for="DatabaseName" class="form-control" />
                <span asp-validation-for="DatabaseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AppWebDBProject/AppWebDB/Views/Database/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using Domain
@model List<Domain.Domain.Database>

<h1>Databases</h1>
<a asp-action="Create" asp-controller="Database">Add a new Database</a>
<table class="table">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Name
            </th>
            <th>
                Username
            </th>
            <th>
                Password
            </th>
            <th>
                Database Name
            </th>
            <th>
                Host
            </th>
            <th>
                Owner Email
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@for (int i = 0; i < Model.Count(); i++)
{
    var item = Model[i];
    <tr>
        <td>@(i + 1)</td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DatabaseName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Host)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Owner.Email)
        </td>
        <td>
            |
            <a asp-action="SeeQuestions" asp-controller="Database" asp-route-id="@item.Id">See questions and answers</a>
        </td>
        <td>
            |
            <a asp-action="Edit" asp-controller="Database" asp-route-id="@item.Id">Edit</a>
        </td>
        <td>
            |
            <a asp-action="Delete" asp-controller="Database" asp-route-id="@item.Id">Delete</a>
        </td>
    </tr>
}
</tbody>

AppWebDBProject/AppWebDB/Views/Database/SeeQuestions.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Domain.Domain.Question>
<h1>All questions and answers:</h1>
<table class="table">
    <thead>
    <th>Question Text</th>
    <th>Question Answer</th>
    </thead>
    <tbody>
        @foreach(var q in Model)
        {
        <tr>
        <td>@q.QuestionText</td>
        <td>@q.QuestionAnswer</td>
        </tr>
        }
    </tbody>
</table>